project:
  type: book
  output-dir: ../docs

book:
  title: "OBIS Manual"
  navbar: 
    background: light
    logo: logo.png
    logo-alt: "OBIS"
    search: true
    left: 
      - text: "Manual"
        file: index.qmd
        # Don't change those lines ####
      - text: "Tutorials"
        file: tutorials.html
      - text: "Packages"
        file: packages.html
      - text: "Find your DwC"
        file: find-dwc.html
        #########
  chapters:
    - index.qmd
    - part: "Overview"
      chapters: 
        - intro.qmd
        - summary.qmd
        - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt



